# Generated by Django 3.0.9 on 2020-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Seoul', '서울특별시')], max_length=30)),
                ('gu', models.CharField(choices=[('Gangnam', '강남구'), ('Songpa', '송파구'), ('Seocho', '서초구'), ('Gangdong', '강동구'), ('Gwanak', '관악구'), ('Yeongdeung', '영등포구'), ('Gangseo', '강서구'), ('Yangcheon', '양천구'), ('Guro', '구로구'), ('Geumcheon', '금천구'), ('Jongno', '종로구'), ('Jung', '중구'), ('Dongdaemun', '동대문구'), ('Jungrang', '중랑구'), ('Mapo', '마포구'), ('Yongsan', '용산구'), ('Seongdong', '성동구'), ('Gwangjin', '광진구'), ('Eunpyeong', '은평구'), ('Seodaemun', '서대문구'), ('Seongbuk', '성북구'), ('Gangbuk', '강북구'), ('Dobong', '도봉구'), ('Nowon', '노원구')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefer_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Seoul', '서울특별시')], max_length=30)),
                ('gu', models.CharField(choices=[('Gangnam', '강남구'), ('Songpa', '송파구'), ('Seocho', '서초구'), ('Gangdong', '강동구'), ('Gwanak', '관악구'), ('Yeongdeung', '영등포구'), ('Gangseo', '강서구'), ('Yangcheon', '양천구'), ('Guro', '구로구'), ('Geumcheon', '금천구'), ('Jongno', '종로구'), ('Jung', '중구'), ('Dongdaemun', '동대문구'), ('Jungrang', '중랑구'), ('Mapo', '마포구'), ('Yongsan', '용산구'), ('Seongdong', '성동구'), ('Gwangjin', '광진구'), ('Eunpyeong', '은평구'), ('Seodaemun', '서대문구'), ('Seongbuk', '성북구'), ('Gangbuk', '강북구'), ('Dobong', '도봉구'), ('Nowon', '노원구')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
