# Generated by Django 3.0.9 on 2020-08-08 10:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=100, verbose_name='크리에이터명')),
                ('creator_photo', models.ImageField(upload_to='creator_photo/%Y/%m/%d/')),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=100, validators=[login.models.min_length_2_validator], verbose_name='닉네임')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Member')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Creator')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Member'),
        ),
    ]
